# Generated by Django 5.1.7 on 2025-03-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artistprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artists',
        ),
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='music', to='core.artistprofile'),
            preserve_default=False,
        ),
    ]
