# Generated by Django 5.1.7 on 2025-03-19 05:07

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[app.core.models.validate_date], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[app.core.models.validate_date], verbose_name='Date of Birth'),
        ),
    ]
