# Generated by Django 5.1.7 on 2025-03-19 05:10

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_artistprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateField(blank=True, null=True, validators=[app.core.models.validate_date], verbose_name='Release Date'),
        ),
    ]
