# Generated by Django 5.1.7 on 2025-03-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_music_artists_music_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artists',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='core.artistprofile'),
        ),
        migrations.DeleteModel(
            name='MusicArtists',
        ),
    ]
