# Generated by Django 5.1.7 on 2025-03-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_music_artists_music_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_musics', to='core.artistprofile'),
        ),
    ]
