# Generated by Django 5.1.7 on 2025-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_music_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
