# Generated by Django 5.1.7 on 2025-03-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_managerprofile_artistprofile_manager_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerprofile',
            options={'verbose_name': 'Manager Profile'},
        ),
    ]
